-- MySQL Script generated by MySQL Workbench
-- 07/23/14 12:54:27
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema localDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `localDB` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `localDB` ;

-- -----------------------------------------------------
-- Table `localDB`.`obdTable`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `localDB`.`obdTable` (
  `id_obd` INT NULL,
  `fecha_rpi` VARCHAR(45) NULL,
  `velocidad` VARCHAR(45) NULL,
  `velocidad_media` VARCHAR(45) NULL,
  `rpm` VARCHAR(45) NULL,
  `temperatura_motor` VARCHAR(45) NULL,
  `motor` VARCHAR(45) NULL,
  `MAF` VARCHAR(45) NULL,
  `MIL` VARCHAR(45) NULL,
  `inyeccion_directa` VARCHAR(45) NULL,
  `inyeccion` VARCHAR(45) NULL,
  `consumo` VARCHAR(45) CHARACTER SET 'big5' NULL,
  `eficiencia_diesel` VARCHAR(45) NULL,
  `eficiencia_gasolina` VARCHAR(45) NULL,
  `DTC` VARCHAR(45) NULL,
  `throttle` VARCHAR(45) NULL,
  `intake_air` VARCHAR(45) NULL,
  `lambda_o2s1_v` VARCHAR(45) NULL,
  `lambda_o2s8_v` VARCHAR(45) NULL,
  `egr` VARCHAR(45) NULL,
  `lambda_o2s3_c` VARCHAR(45) NULL,
  `run_time` VARCHAR(45) NULL,
  `fuel_level` VARCHAR(45) NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `localDB`.`gprmTable`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `localDB`.`gprmTable` (
  `id_gps` VARCHAR(45) NULL,
  `fecha_rpi` VARCHAR(45) NULL,
  `fecha_gps` VARCHAR(45) NULL,
  `UTCTime` VARCHAR(45) NULL,
  `latitud` VARCHAR(45) NULL,
  `N_S` VARCHAR(45) NULL,
  `longitud` VARCHAR(45) NULL,
  `E_W` VARCHAR(45) NULL,
  `velocidad` VARCHAR(45) NULL,
  `modo` VARCHAR(45) NULL,
  `estadoGPS` VARCHAR(45) NULL,
  `rumbo` VARCHAR(45) NULL,
  `distancia` VARCHAR(45) NULL,
  `km_recorridos` VARCHAR(45) NULL)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
